[package]
name = "raspicc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
videocore = "0.1.3"
libc = "0.1"